
function chunkArrayInGroups(arr, size) {
    var myArray = [];
    for (var i = 0; i < arr.length; i += size) {
        myArray.push(arr.slice(i, i + size));
    }
    return myArray;
}
var arrData = [
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
    "<tr><td>XYZ-XYZ</td><td>210921</td><td>Lorem ipsum</td><td></td><td></td><td>Lorem ipsum</td><td></td><td>Loreeeeeeeem</td><td></td><td>BKSKALNWD</td><td>1/12/2024</td><td>1/12/2024</td><td>Released</td><td>WADKNLSW</td><td>Order Line</td><td>Lorem-2020-0000007</td><td>Lorem Ipsum Lorem Ipsum Lorem Ipsum</td><td></td><td></td><td>ASG-ASDW</td><td>Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem Loreeeeeeeem</td><td align='right'>174,270</td><td align='right'>174,270</td><td></td><td></td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td><td></td><td align='right'>140</td><td align='right'>0</td><td align='right'>0</td><td align='right'>0</td><td align='right'>174,270</td></tr>",
];
dataChunk = chunkArrayInGroups(arrData, 100);

document.getElementById("index").innerHTML = "0";
document.getElementById("page").innerHTML = "1";
document.getElementById("rowof").innerHTML = "of " + dataChunk.length;
document.getElementById("tableBody").innerHTML = dataChunk[0].join(""); // first page
// Arrow onclick listener
$("#navContainer .arrow").on("click", function () {
    var index = parseInt($("#index").html());
    var currentPage = parseInt($("#page").html());
    var next = this.id === "next";
    var prev = this.id === "prev";

    if (index === 0 && prev) return; // end of prev
    else if (index === dataChunk.length - 1 && next) return; // end of next
    else if (prev) {
        index -= 1;
        $("#index").html(index.toString());
        currentPage -= 1;
        $("#page").html(currentPage.toString());
    } else {
        // next
        index += 1;
        $("#index").html(index.toString());
        currentPage += 1;
        $("#page").html(currentPage.toString());
    }
    // Insert to table body
    document.getElementById("tableBody").innerHTML = dataChunk[index].join("");
});
